// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UI.Data;

#nullable disable

namespace UI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241201142223_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("TableNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 12, 2, 16, 22, 23, 775, DateTimeKind.Local).AddTicks(9330),
                            PersonId = "1",
                            RestaurantId = 1,
                            TableNum = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 12, 3, 16, 22, 23, 775, DateTimeKind.Local).AddTicks(9379),
                            PersonId = "2",
                            RestaurantId = 2,
                            TableNum = 2
                        });
                });

            modelBuilder.Entity("UI.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("TableNum")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 11, 30, 16, 22, 23, 775, DateTimeKind.Local).AddTicks(9392),
                            PersonId = "1",
                            RestaurantId = 1,
                            TableNum = 1,
                            Text = "Great food!"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 11, 29, 16, 22, 23, 775, DateTimeKind.Local).AddTicks(9396),
                            PersonId = "2",
                            RestaurantId = 2,
                            TableNum = 2,
                            Text = "Nice ambiance!"
                        });
                });

            modelBuilder.Entity("UI.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 11, 21, 16, 22, 23, 775, DateTimeKind.Local).AddTicks(9410),
                            Description = "Restaurant A is opening soon!",
                            Photo = new byte[] { 0, 0, 0, 0, 0 }
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 11, 26, 16, 22, 23, 775, DateTimeKind.Local).AddTicks(9412),
                            Description = "New menu in Restaurant B!",
                            Photo = new byte[] { 0, 0, 0, 0, 0 }
                        });
                });

            modelBuilder.Entity("UI.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e45a087d-2b12-4dc6-a6aa-9e5bf856e494",
                            Email = "user1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "John",
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "testpasswordhash",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a22978e-3628-4fc5-9b30-4aa6bdd63a3e",
                            Surname = "Doe",
                            ThirdName = "Smith",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "302b8f63-976d-42dd-969e-bbaf233f3886",
                            Email = "user2@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Jane",
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "testpasswordhash",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad7e917b-c221-426a-8d97-5f6ca50d6d98",
                            Surname = "Smith",
                            ThirdName = "Doe",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("UI.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FavoriteLinks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("PointX")
                        .HasColumnType("float");

                    b.Property<double>("PointY")
                        .HasColumnType("float");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("TelNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "просп. Миру, 10",
                            Description = " Gusto – перший космополітичний заклад у Рівному формату gastro salon, місце зустрічі однодумців, тих, хто вважає основною метою життя – насолода у всіх її проявах. Для тебе тут поєднали найяскравіші смаки страв із чудовими напоями, створили затишну атмосферу, доклали максимум зусиль, щоб звичайне задоволення від їжі перетворити на ейфорію.",
                            FavoriteLinks = "https://grill-bar-dvir.choiceqr.com/",
                            Photo = new byte[] { 0, 0, 0, 0, 0 },
                            PointX = 50.624509699999997,
                            PointY = 26.244995299999999,
                            Stars = 5,
                            TelNum = "+38(095) 471 00 31",
                            Title = "Ресторан \"Gusto gastro salon\""
                        },
                        new
                        {
                            Id = 2,
                            Address = "вул. Степана Бандери 24А",
                            Description = "Gastropub Father відчинив свої двері в 2016 році. Концепцією закладу є виготовлення крафтового пива. Любителі смачної кухні можуть сповна насолодитися стравами англо-британської кухні. Особливостями нашого меню є 6 видів крафтового пива, два сорти з яких у 2020 році здобули перше та друге місце на конкурсі EAST EUROPEAN BEER AWARD 2020. Заклад приємно порадує великою різноманітністю страв: салати, смачні супи, м’ясні та рибні страви, птиця, закуски а також неповторні десерти. Затишна атмосфера, цікаві декорації інтер’єру і сміливі дизайнерські рішення дозволять вам затишно провести свій час. У барному меню вас чекає широкий асортимент алкогольних коктейлів і безалкогольних напоїв, що дозволить знайти ідеальний варіант для кожного гостя. На вихідних в закладі грає жива музика, транслюються футбольні матчі. Ви неодмінно залишитеся задоволені і побажаєте знову повернутися в gastropub Father .\"",
                            FavoriteLinks = "https://gastropubfather.com/",
                            Photo = new byte[] { 0, 0, 0, 0, 0 },
                            PointX = 50.613010099999997,
                            PointY = 26.254899399999999,
                            Stars = 4,
                            TelNum = "+38(097) 559 55 50",
                            Title = "Гастропаб \"Father\""
                        },
                        new
                        {
                            Id = 3,
                            Address = "вул. 16 Липня, 7a",
                            Description = "У ресторані \"Fortissimo\" представлені різноманітні алкогольні напої та коктейльні композиції. Крім того можна смачно поїсти, оскільки в меню широкий вибір салатів, гарячих і холодних страв. Авторська кухня американського та європейського зразку. Оскільки ресторан працює цілодобово - він відповідає ритму життя динамічного містечка західної України.",
                            FavoriteLinks = "https://fortissimo.choiceqr.com/",
                            Photo = new byte[] { 0, 0, 0, 0, 0 },
                            PointX = 50.450000000000003,
                            PointY = 30.52,
                            Stars = 5,
                            TelNum = "+38(097) 898 15 51",
                            Title = "Автентичний стріт-бар \"Fortissimo\""
                        },
                        new
                        {
                            Id = 4,
                            Address = "вул. Княгині Ольги, 1а",
                            Description = "New York Street Pizza\" (ТЦ \"Покровський\") – яскравий та стильний заклад всеукраїнської мережі, що знаходиться у мальовничому куточку міста поблизу центрального парку. Приємне світло, теплий дизайн та зручна зональність створюють надзвичайну затишну атмосферу в закладі, доповнену ароматом свіжоспеченої піци та кави. На першому поверсі – столики для двох та дивани для довгих посиденьок, а також банкетна зала. На другому поверсі гостям відкривається панорама міста. В теплу пору року можна займати місця на терасі. Щодня в закладі подають сніданки, в обідню пору можна замовити комплекс: на вибір українська або японська кухня.",
                            FavoriteLinks = "https://nysp.com.ua/menu-rest",
                            Photo = new byte[] { 0, 0, 0, 0, 0 },
                            PointX = 50.618630000000003,
                            PointY = 26.245721700000001,
                            Stars = 4,
                            TelNum = "+38 (068) 007 00 72",
                            Title = "Ресторан \"Nеw York Strееt Pіzzа\""
                        },
                        new
                        {
                            Id = 5,
                            Address = "вул. Симона Петлюри, 3",
                            Description = "Ресторан гриль-бар \"Dvir\" розташований у центральній частині міста Рівного. Має унікальний інтер'єр та розташування, створюючи особливу атмосферу для своїх гостей. Пропонує своїм відвідувачам страви української та європейської кухонь, а також великий вибір напоїв на будь-який смак. Привітний персонал забезпечить якісний сервіс. У закладі є дуже велика та затишна літня тераса, де приємно посидіти з друзями або в сімейному колі.\r\n",
                            FavoriteLinks = "https://grill-bar-dvir.choiceqr.com/",
                            Photo = new byte[] { 0, 0, 0, 0, 0 },
                            PointX = 50.620991199999999,
                            PointY = 26.245221600000001,
                            Stars = 4,
                            TelNum = "+38 (068) 072 40 46",
                            Title = "Grill&Bar DVIR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UI.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UI.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UI.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UI.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UI.Models.Booking", b =>
                {
                    b.HasOne("UI.Models.Person", "Person")
                        .WithMany("Bookings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UI.Models.Restaurant", "Restaurant")
                        .WithMany("Bookings")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("UI.Models.Feedback", b =>
                {
                    b.HasOne("UI.Models.Person", "Person")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UI.Models.Restaurant", "Restaurant")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("UI.Models.Person", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("UI.Models.Restaurant", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
